In [1]:
import numpy as np 
from matplotlib import pyplot as plt 



In [2]:
a = np.array([[0.5,0.5,0.25],
              [0.25,0,0.25],
              [0.25,0.5,0.5]])


In [3]:
print(a)


[[0.5  0.5  0.25]
 [0.25 0.   0.25]
 [0.25 0.5  0.5 ]]


In [4]:
xtoady = np.array([[0.5],[0],[0.5]])

In [5]:
print(xtoady)

[[0.5]
 [0. ]
 [0.5]]


In [6]:
print(a@xtoady)

[[0.375]
 [0.25 ]
 [0.375]]


In [7]:
for k in range(1,50):
    print(k)
    atom = (a@xtoady)
    print(atom)
    xtoday = atom

1
[[0.375]
 [0.25 ]
 [0.375]]
2
[[0.375]
 [0.25 ]
 [0.375]]
3
[[0.375]
 [0.25 ]
 [0.375]]
4
[[0.375]
 [0.25 ]
 [0.375]]
5
[[0.375]
 [0.25 ]
 [0.375]]
6
[[0.375]
 [0.25 ]
 [0.375]]
7
[[0.375]
 [0.25 ]
 [0.375]]
8
[[0.375]
 [0.25 ]
 [0.375]]
9
[[0.375]
 [0.25 ]
 [0.375]]
10
[[0.375]
 [0.25 ]
 [0.375]]
11
[[0.375]
 [0.25 ]
 [0.375]]
12
[[0.375]
 [0.25 ]
 [0.375]]
13
[[0.375]
 [0.25 ]
 [0.375]]
14
[[0.375]
 [0.25 ]
 [0.375]]
15
[[0.375]
 [0.25 ]
 [0.375]]
16
[[0.375]
 [0.25 ]
 [0.375]]
17
[[0.375]
 [0.25 ]
 [0.375]]
18
[[0.375]
 [0.25 ]
 [0.375]]
19
[[0.375]
 [0.25 ]
 [0.375]]
20
[[0.375]
 [0.25 ]
 [0.375]]
21
[[0.375]
 [0.25 ]
 [0.375]]
22
[[0.375]
 [0.25 ]
 [0.375]]
23
[[0.375]
 [0.25 ]
 [0.375]]
24
[[0.375]
 [0.25 ]
 [0.375]]
25
[[0.375]
 [0.25 ]
 [0.375]]
26
[[0.375]
 [0.25 ]
 [0.375]]
27
[[0.375]
 [0.25 ]
 [0.375]]
28
[[0.375]
 [0.25 ]
 [0.375]]
29
[[0.375]
 [0.25 ]
 [0.375]]
30
[[0.375]
 [0.25 ]
 [0.375]]
31
[[0.375]
 [0.25 ]
 [0.375]]
32
[[0.375]
 [0.25 ]
 [0.375]]
33
[[0.375]
 [0.2